version: "3"

services:
  teller:
    image: ginco/teller:v2.70.1
    ports:
      - "50051:50051"
    command: -f /root/configs/config.toml
    volumes:
      - "./configs/teller/config.toml:/root/configs/config.toml"
    env_file:
      - "./envs/teller/.env"
  # postbox:
  #   image: ginco/postbox:v0.43.0
  #   command: -f /root/configs/config.toml
  #   volumes:
  #     - "./configs/postbox/config.toml:/root/configs/config.toml"
  #   env_file:
  #     - "./envs/postbox/.env"
  # postbox-gateway:
  #   image: ginco/postbox-gateway:v0.43.0
  #   ports:
  #     - "8080:8080"
  #   command: >
  #     -cpu=2
  #     -port=8080
  #     -endpoint="postbox:50051"
