proto_outdir = "./vendor"

[[dependencies]]
    target = "github.com/envoyproxy/protoc-gen-validate"
    revision = "2fe48adf079caf32135cb3327377a7b5488e350b"
    ignores = ["gogoproto", "java", "tests", "vendor"]

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/global"
    revision = "60452cd858f8f88962ef2a6772fa0d695659b81f"
    path = "gincoinc/global"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/adamant/global"
    revision = "60452cd858f8f88962ef2a6772fa0d695659b81f"
    path = "gincoinc/adamant/global"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/adamant/teller"
    revision = "60452cd858f8f88962ef2a6772fa0d695659b81f"
    path = "gincoinc/adamant/teller"
