proto_outdir = "./vendor"

[[dependencies]]
    target = "github.com/envoyproxy/protoc-gen-validate"
    revision = "2fe48adf079caf32135cb3327377a7b5488e350b"
    ignores = ["gogoproto", "java", "tests", "vendor"]

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/global"
    revision = "03bbe4dc905db773ed4b1cbac9682f3e004ef916"
    path = "gincoinc/global"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/adamant/global"
    revision = "03bbe4dc905db773ed4b1cbac9682f3e004ef916"
    path = "gincoinc/adamant/global"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/adamant/teller"
    revision = "18469cbd50d41c71aa1120b3ff5251e71eea9484"
    path = "gincoinc/adamant/teller"

[[dependencies]]
    target = "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis"
    branch = "master"
    ignores = ["google/rpc"]
