proto_outdir = "./vendor"

[[dependencies]]
    target = "github.com/envoyproxy/protoc-gen-validate"
    revision = "2fe48adf079caf32135cb3327377a7b5488e350b"
    ignores = ["gogoproto", "java", "tests", "vendor"]

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/global"
    revision = "da9b7baee6e134ca727c38598a32ac92c46d2895"
    path = "gincoinc/global"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/adamant/global"
    revision = "da9b7baee6e134ca727c38598a32ac92c46d2895"
    path = "gincoinc/adamant/global"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/adamant/teller"
    revision = "da9b7baee6e134ca727c38598a32ac92c46d2895"
    path = "gincoinc/adamant/teller"
