proto_outdir = "./vendor"

[[dependencies]]
    target = "github.com/envoyproxy/protoc-gen-validate"
    revision = "2fe48adf079caf32135cb3327377a7b5488e350b"
    ignores = ["gogoproto", "java", "tests", "vendor"]

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/global"
    revision = "715a24d8a969f1145a9a561d8a8034d16bafd069"
    path = "gincoinc/global"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/adamant/global"
    revision = "715a24d8a969f1145a9a561d8a8034d16bafd069"
    path = "gincoinc/adamant/global"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/adamant/teller"
    revision = "715a24d8a969f1145a9a561d8a8034d16bafd069"
    path = "gincoinc/adamant/teller"
