proto_outdir = "./vendor"

[[dependencies]]
    target = "github.com/envoyproxy/protoc-gen-validate"
    revision = "2fe48adf079caf32135cb3327377a7b5488e350b"
    ignores = ["gogoproto", "java", "tests", "vendor"]
    protocol = "https"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/global"
    revision = "c0cb89acf56bb524d32fcf794e06596acb40f91a"
    path = "gincoinc/global"
    protocol = "ssh"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/adamant/global"
    revision = "c0cb89acf56bb524d32fcf794e06596acb40f91a"
    path = "gincoinc/adamant/global"
    protocol = "ssh"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/adamant/teller"
    revision = "c0cb89acf56bb524d32fcf794e06596acb40f91a"
    path = "gincoinc/adamant/teller"
    protocol = "ssh"
