proto_outdir = "./vendor"

[[dependencies]]
    target = "github.com/envoyproxy/protoc-gen-validate"
    revision = "2fe48adf079caf32135cb3327377a7b5488e350b"
    ignores = ["gogoproto", "java", "tests", "vendor"]
    protocol = "https"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/global"
    revision = "f83b71681cfe9cf11ed8a95d67f08cc4f50203b1"
    path = "gincoinc/global"
    protocol = "ssh"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/adamant/global"
    revision = "f83b71681cfe9cf11ed8a95d67f08cc4f50203b1"
    path = "gincoinc/adamant/global"
    protocol = "ssh"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/adamant/teller"
    revision = "f83b71681cfe9cf11ed8a95d67f08cc4f50203b1"
    path = "gincoinc/adamant/teller"
    protocol = "ssh"
