proto_outdir = "./vendor"

[[dependencies]]
    target = "github.com/envoyproxy/protoc-gen-validate"
    revision = "2fe48adf079caf32135cb3327377a7b5488e350b"
    ignores = ["gogoproto", "java", "tests", "vendor"]
    protocol = "https"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/global"
    revision = "39f8ecef2bc1ce12f969c0afe7439ff46d982231"
    path = "gincoinc/global"
    protocol = "ssh"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/adamant/global"
    revision = "39f8ecef2bc1ce12f969c0afe7439ff46d982231"
    path = "gincoinc/adamant/global"
    protocol = "ssh"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/adamant/teller"
    revision = "39f8ecef2bc1ce12f969c0afe7439ff46d982231"
    path = "gincoinc/adamant/teller"
    protocol = "ssh"
