proto_outdir = "./vendor"

[[dependencies]]
    target = "github.com/envoyproxy/protoc-gen-validate"
    revision = "2fe48adf079caf32135cb3327377a7b5488e350b"
    ignores = ["gogoproto", "java", "tests", "vendor"]
    protocol = "https"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/global"
    revision = "98207c2ebf2e8b3caf21619e07f27150c30120e8"
    path = "gincoinc/global"
    protocol = "ssh"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/adamant/global"
    revision = "98207c2ebf2e8b3caf21619e07f27150c30120e8"
    path = "gincoinc/adamant/global"
    protocol = "ssh"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/adamant/teller"
    revision = "98207c2ebf2e8b3caf21619e07f27150c30120e8"
    path = "gincoinc/adamant/teller"
    protocol = "ssh"
