proto_outdir = "./api/proto"

[[dependencies]]
  target = "github.com/envoyproxy/protoc-gen-validate"
  revision = "v0.2.0-java"
  ignores = ["gogoproto", "java", "tests", "vendor"]

[[dependencies]]
  target = "github.com/GincoInc/protobuf/proto/gincoinc/global"
  revision = "v1.71.0"
  path = "gincoinc/global"

[[dependencies]]
  target = "github.com/GincoInc/protobuf/proto/gincoinc/adamant/global"
  revision = "v1.71.0"
  path = "gincoinc/adamant/global"

[[dependencies]]
  target = "github.com/GincoInc/protobuf/proto/gincoinc/adamant/teller"
  revision = "v1.71.0"
  path = "gincoinc/adamant/teller"
