proto_outdir = "./vendor"

[[dependencies]]
    target = "github.com/envoyproxy/protoc-gen-validate"
    revision = "2fe48adf079caf32135cb3327377a7b5488e350b"
    ignores = ["gogoproto", "java", "tests", "vendor"]

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/global"
    revision = "9cb93da774025b2df30e8a36fa71b7e9325e849e"
    path = "gincoinc/global"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/adamant/global"
    revision = "9cb93da774025b2df30e8a36fa71b7e9325e849e"
    path = "gincoinc/adamant/global"

[[dependencies]]
    target = "github.com/GincoInc/protobuf/gincoinc/adamant/teller"
    revision = "9cb93da774025b2df30e8a36fa71b7e9325e849e"
    path = "gincoinc/adamant/teller"
